--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: existing-vpc
  region: us-east-1
  version: "1.21"
vpc:
  id: vpc-0e88c3c17fb0c7cca
  subnets:
    private:
      us-east-1a:
        id: subnet-0699d559ea175cac2
      us-east-1b:
        id: subnet-049a9d986dc0d9aa5
    public:
      us-east-1a:
        id: subnet-0e4f8a8dda322fac4
      us-east-1b:
        id: subnet-0068c08ea23be99dc
managedNodeGroups:
- name: general
  privateNetworking: true
  instanceType: t3.small
  desiredCapacity: 1
